### ISSUE TITLE
no reconnection after server restart

### ISSUE THREAD

**Issue by nicolas-ginder** [KristjanTammekivi/Haredo#203]
Haredo 2.x does not reconnect to RabbitMq server after a restart. It is easy to reproduce by connecting to Rabbit using Haredo and do a simple restart of RabbitMq server. Our Rabbit cluster is deployed in GKE where frequent restarts are caused by pod movements.
No isssues with 1.3.2

**Comment by KristjanTammekivi** [comment]
Hmm i'll try to replicate, we usually don't restart Rabbit but recently I've started upgrading rabbit in staging and I noticed reconnections

**Comment by KristjanTammekivi** [comment]
I'm able to replicate it, I think it's not about haredo but in either amqplib or rabbitmq, going to test older versions of them. Connection is reestablished just fine, publishing continues, consume promise resolves with a consumer tag but for some reason no messages arrive in it.

**Comment by KristjanTammekivi** [comment]
Well now I'm just confused, tested amqplib 1.5.2 which is a lot older than the one I used in haredo 1.3.2 and it doesn't work there, and You say old haredo works, so it must be my code after all

**Comment by KristjanTammekivi** [comment]
Found the mistake, easy fix incoming

**Comment by KristjanTammekivi** [comment]
Released v2.6.3
