### ISSUE TITLE
Throttle subscribe

### ISSUE THREAD

**Issue by tobiaslins** [KristjanTammekivi/Haredo#232]
Is it possible to limit the jobs processed using .subscribe? 
We are passing an async function to subscribe and it doesn't wait until it is finished until taking a new one.

It would be amazing if we could add some limits for processing. eg
```
 limiter: {
    max: 10,
    duration: 1000
  }
```

this would mean it just allows to process 10 messages per second. Would love to hear your thoughts on this

&& great library. Thanks for creating it :)

**Comment by KristjanTammekivi** [comment]
Closed by https://github.com/KristjanTammekivi/Haredo/commit/1937ee83331545a0c64dffc6f77d75b345252541
