### ISSUE TITLE
Can you describe why advantages and cons of your library in comparison with amqplib?

### ISSUE THREAD

**Issue by gustawdaniel** [KristjanTammekivi/Haredo#357]
I think that everybody who need to work with RabbitMQ on node js, will compare [amqplib](https://www.npmjs.com/package/amqplib) that have 1M download weekly with your library.

It would be super useful if in README, you would comparison and describe who should choose which library.

**Comment by KristjanTammekivi** [comment]
This is a wrapper over amqplib so by definition it can't really have more downloads than amqplib. As for the advantages over just using barebones amqplib I've gone over it (somewhat concisely) in the first two points of the README.md and I don't really intend to expand on it.
